name: Docker Image CI

on:
  schedule:
    - cron: "0 11 * * 3"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: corilus/postfix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # for proper signature verification
          submodules: true # for shunit2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build alpine image
        run: |
          docker build . \
            --pull=true \
            --file=alpine/Dockerfile \
            --tag="$IMAGE_NAME:alpine-${{github.run_number}}" \
            --label="org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
            --label="org.opencontainers.image.revision=$GITHUB_SHA" \
            --label="org.opencontainers.image.created=$(date --rfc-3339=seconds)"

      - name: Build debian image
        run: |
          docker build . \
            --pull=true \
            --file=alpine/Dockerfile \
            --tag="$IMAGE_NAME:debian-${{github.run_number}}" \
            --label="org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
            --label="org.opencontainers.image.revision=$GITHUB_SHA" \
            --label="org.opencontainers.image.created=$(date --rfc-3339=seconds)"

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push images to Docker Hub registry
        if: github.ref == 'refs/heads/master'
        run: |
          docker push $IMAGE_NAME:alpine-${{github.run_number}}
          docker push $IMAGE_NAME:debian-${{github.run_number}}
